<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Collection;

class CollectionSeeder extends Seeder
{
    public function run(): void
    {
        $forms = [

            // ──────────────────────────────────────────────────────────────
            // FORM 1 — Featured / Hero Collections
            // Shown on homepage banners, top of store
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'New Arrivals',
                'slug'            => 'new-arrivals',
                'description'     => 'Fresh gear just landed — explore the latest products across all sports.',
                'type'            => 'auto',
                'rules'           => [['field' => 'is_new', 'operator' => 'equals', 'value' => true]],
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 1,
                'seo_title'       => 'New Arrivals — Latest Sports Gear | Decathlon',
                'seo_description' => 'Shop the newest arrivals in sports equipment, apparel and footwear at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Best Sellers',
                'slug'            => 'best-sellers',
                'description'     => 'Our most popular products loved by athletes across India.',
                'type'            => 'auto',
                'rules'           => [['field' => 'is_best_seller', 'operator' => 'equals', 'value' => true]],
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 2,
                'seo_title'       => 'Best Sellers — Top Rated Sports Products | Decathlon',
                'seo_description' => 'Discover Decathlon\'s best selling sports equipment, shoes and activewear.',
                'status'          => true,
            ],
            [
                'name'            => 'Featured Products',
                'slug'            => 'featured-products',
                'description'     => 'Hand-picked products curated by our sports experts.',
                'type'            => 'auto',
                'rules'           => [['field' => 'is_featured', 'operator' => 'equals', 'value' => true]],
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 3,
                'seo_title'       => 'Featured Products | Decathlon',
                'seo_description' => 'Editor\'s picks — the best sports products selected by Decathlon experts.',
                'status'          => true,
            ],
            [
                'name'            => 'Sale & Offers',
                'slug'            => 'sale-offers',
                'description'     => 'Great deals on top sports brands — limited time offers.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 4,
                'seo_title'       => 'Sale & Offers — Sports Deals | Decathlon',
                'seo_description' => 'Shop discounted sports gear, apparel and footwear at Decathlon. Limited time offers.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 2 — By Sport / Activity
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Football Essentials',
                'slug'            => 'football-essentials',
                'description'     => 'Everything you need for football — boots, balls, kits, gloves and more.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 10,
                'seo_title'       => 'Football Gear & Equipment | Decathlon',
                'seo_description' => 'Shop football boots, balls, jerseys and accessories at Decathlon India.',
                'status'          => true,
            ],
            [
                'name'            => 'Cricket Must-Haves',
                'slug'            => 'cricket-must-haves',
                'description'     => 'Bats, pads, helmets and complete cricket kits for all levels.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 11,
                'seo_title'       => 'Cricket Equipment & Gear | Decathlon',
                'seo_description' => 'Buy cricket bats, balls, pads, gloves and full kits at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Running Shop',
                'slug'            => 'running-shop',
                'description'     => 'Shoes, apparel, trackers and hydration for every runner.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 12,
                'seo_title'       => 'Running Shoes & Gear | Decathlon',
                'seo_description' => 'Shop road and trail running shoes, clothing and accessories at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Yoga & Mindfulness',
                'slug'            => 'yoga-mindfulness',
                'description'     => 'Mats, blocks, straps, apparel and props for your yoga practice.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 13,
                'seo_title'       => 'Yoga Mats, Props & Clothing | Decathlon',
                'seo_description' => 'Find yoga mats, blocks, straps and breathable yoga wear at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Gym & Fitness',
                'slug'            => 'gym-fitness',
                'description'     => 'Build your home gym — dumbbells, benches, resistance bands and more.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 14,
                'seo_title'       => 'Gym Equipment & Fitness Gear | Decathlon',
                'seo_description' => 'Shop gym equipment including dumbbells, barbells, benches and cardio machines.',
                'status'          => true,
            ],
            [
                'name'            => 'Cycling Collection',
                'slug'            => 'cycling-collection',
                'description'     => 'Bikes, helmets, jerseys, lights and everything cyclists need.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => true,
                'sort_order'      => 15,
                'seo_title'       => 'Bikes & Cycling Gear | Decathlon',
                'seo_description' => 'Explore road bikes, mountain bikes, helmets and cycling accessories at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Swimming & Water Sports',
                'slug'            => 'swimming-water-sports',
                'description'     => 'Swimwear, goggles, caps, fins, surfboards and water sports gear.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 16,
                'seo_title'       => 'Swimming & Water Sports Equipment | Decathlon',
                'seo_description' => 'Shop swimwear, goggles, surfboards and water sports gear at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Badminton Zone',
                'slug'            => 'badminton-zone',
                'description'     => 'Rackets, shuttles, nets, shoes and apparel for badminton lovers.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 17,
                'seo_title'       => 'Badminton Rackets, Shuttles & Gear | Decathlon',
                'seo_description' => 'Buy badminton rackets, shuttlecocks, shoes and accessories at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Hiking & Trekking',
                'slug'            => 'hiking-trekking',
                'description'     => 'Boots, backpacks, tents, trekking poles and trail essentials.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 18,
                'seo_title'       => 'Hiking Boots, Backpacks & Trekking Gear | Decathlon',
                'seo_description' => 'Explore hiking boots, backpacks, tents and trekking poles at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Camping Gear',
                'slug'            => 'camping-gear',
                'description'     => 'Tents, sleeping bags, camp furniture, lighting and cooking essentials.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 19,
                'seo_title'       => 'Camping Tents, Sleeping Bags & Outdoor Gear | Decathlon',
                'seo_description' => 'Shop tents, sleeping bags, camp lights and cooking gear at Decathlon.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 3 — By Gender / Audience
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Men\'s Sports',
                'slug'            => 'mens-sports',
                'description'     => 'Performance apparel, footwear and equipment designed for men.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 30,
                'seo_title'       => 'Men\'s Sports Clothing & Gear | Decathlon',
                'seo_description' => 'Shop men\'s sports clothing, shoes and equipment at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Women\'s Sports',
                'slug'            => 'womens-sports',
                'description'     => 'Activewear, footwear and sports gear crafted for women.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 31,
                'seo_title'       => 'Women\'s Sports Clothing & Gear | Decathlon',
                'seo_description' => 'Shop women\'s sports clothing, shoes and accessories at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Kids Sports',
                'slug'            => 'kids-sports',
                'description'     => 'Fun and safe sports gear for children of all ages.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 32,
                'seo_title'       => 'Kids Sports Equipment & Clothing | Decathlon',
                'seo_description' => 'Shop sports shoes, clothing and gear designed for kids at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Beginner Starter Kits',
                'slug'            => 'beginner-starter-kits',
                'description'     => 'Everything a beginner needs to start their sports journey — curated kits at great value.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 33,
                'seo_title'       => 'Sports Starter Kits for Beginners | Decathlon',
                'seo_description' => 'Affordable starter kits for beginners across all sports at Decathlon.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 4 — By Feature / Technology
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Waterproof & Weather-Proof',
                'slug'            => 'waterproof-weather-proof',
                'description'     => 'Stay dry in any condition — waterproof jackets, shoes and gear.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 40,
                'seo_title'       => 'Waterproof Sports Gear & Clothing | Decathlon',
                'seo_description' => 'Shop waterproof jackets, shoes and outdoor gear at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Eco-Friendly & Sustainable',
                'slug'            => 'eco-friendly-sustainable',
                'description'     => 'Products made from recycled or sustainable materials — good for sport, good for planet.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 41,
                'seo_title'       => 'Eco-Friendly Sports Products | Decathlon',
                'seo_description' => 'Shop sustainable and recycled material sports gear at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Lightweight Performance',
                'slug'            => 'lightweight-performance',
                'description'     => 'Ultra-light gear for athletes who demand speed and agility.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 42,
                'seo_title'       => 'Lightweight Sports Gear | Decathlon',
                'seo_description' => 'Discover ultra-lightweight sports equipment and apparel at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'UV Protection Gear',
                'slug'            => 'uv-protection-gear',
                'description'     => 'Sun-safe sports clothing and accessories with UPF 30–50+ protection.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 43,
                'seo_title'       => 'UV Protection Sports Clothing | Decathlon',
                'seo_description' => 'Shop UPF 30 to 50+ sports clothing for outdoor activities at Decathlon.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 5 — Seasonal / Occasion
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Summer Sports Essentials',
                'slug'            => 'summer-sports-essentials',
                'description'     => 'Beat the heat with breathable, moisture-wicking summer sports gear.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 50,
                'seo_title'       => 'Summer Sports Gear & Clothing | Decathlon',
                'seo_description' => 'Stay cool this summer with breathable sports clothing and equipment from Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Monsoon Sports',
                'slug'            => 'monsoon-sports',
                'description'     => 'Waterproof and rain-ready gear for your active monsoon season.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 51,
                'seo_title'       => 'Monsoon Sports Gear | Decathlon',
                'seo_description' => 'Shop rain-ready sports gear for the monsoon season at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Winter Sports Collection',
                'slug'            => 'winter-sports-collection',
                'description'     => 'Warm, insulated and windproof gear for cold-weather training and snow sports.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 52,
                'seo_title'       => 'Winter Sports Clothing & Equipment | Decathlon',
                'seo_description' => 'Shop thermal layers, ski gear and cold-weather sports products at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Gift Ideas for Sports Lovers',
                'slug'            => 'gift-ideas-sports',
                'description'     => 'Perfect gifts for athletes — curated products across all sports and budgets.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 53,
                'seo_title'       => 'Sports Gift Ideas | Decathlon',
                'seo_description' => 'Find the perfect sports gift at Decathlon — for all budgets and all sports.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 6 — Price / Value
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Under ₹999',
                'slug'            => 'under-999',
                'description'     => 'Quality sports products under ₹999 — sport shouldn\'t break the bank.',
                'type'            => 'auto',
                'rules'           => [['field' => 'price', 'operator' => 'less_than', 'value' => 999]],
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 60,
                'seo_title'       => 'Sports Products Under ₹999 | Decathlon',
                'seo_description' => 'Affordable sports gear, clothing and accessories under ₹999 at Decathlon.',
                'status'          => true,
            ],
            [
                'name'            => 'Under ₹1999',
                'slug'            => 'under-1999',
                'description'     => 'Great value sports products under ₹1999.',
                'type'            => 'auto',
                'rules'           => [['field' => 'price', 'operator' => 'less_than', 'value' => 1999]],
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 61,
                'seo_title'       => 'Sports Products Under ₹1999 | Decathlon',
                'seo_description' => 'Buy quality sports gear under ₹1999 at Decathlon India.',
                'status'          => true,
            ],
            [
                'name'            => 'Premium Sports Gear',
                'slug'            => 'premium-sports-gear',
                'description'     => 'Professional-grade equipment and apparel for serious athletes.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 62,
                'seo_title'       => 'Premium Sports Equipment | Decathlon',
                'seo_description' => 'Shop high-performance, premium sports gear at Decathlon India.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 7 — By Brand (Decathlon Own Brands)
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Quechua — Outdoor & Trekking',
                'slug'            => 'quechua-collection',
                'description'     => 'Explore Quechua\'s full range of hiking, camping and mountain gear.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 70,
                'seo_title'       => 'Quechua Hiking & Camping Gear | Decathlon',
                'seo_description' => 'Shop all Quechua products — tents, backpacks, hiking boots and more.',
                'status'          => true,
            ],
            [
                'name'            => 'Kipsta — Team Sports',
                'slug'            => 'kipsta-collection',
                'description'     => 'Kipsta\'s football, basketball, volleyball and team sports equipment.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 71,
                'seo_title'       => 'Kipsta Team Sports Gear | Decathlon',
                'seo_description' => 'Shop Kipsta footballs, jerseys, boots and team sports accessories.',
                'status'          => true,
            ],
            [
                'name'            => 'Kalenji — Running',
                'slug'            => 'kalenji-collection',
                'description'     => 'Kalenji running shoes and apparel for road, trail and track.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 72,
                'seo_title'       => 'Kalenji Running Shoes & Apparel | Decathlon',
                'seo_description' => 'Shop Kalenji running shoes and sports clothing for all runners.',
                'status'          => true,
            ],
            [
                'name'            => 'Domyos — Fitness',
                'slug'            => 'domyos-collection',
                'description'     => 'Domyos fitness equipment, gym apparel and yoga accessories.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 73,
                'seo_title'       => 'Domyos Fitness Gear & Gym Equipment | Decathlon',
                'seo_description' => 'Shop Domyos gym equipment, fitness clothing and yoga accessories.',
                'status'          => true,
            ],
            [
                'name'            => 'Artengo — Racket Sports',
                'slug'            => 'artengo-collection',
                'description'     => 'Artengo tennis, badminton and table tennis rackets and accessories.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 74,
                'seo_title'       => 'Artengo Racket Sports Gear | Decathlon',
                'seo_description' => 'Shop Artengo tennis, badminton and table tennis equipment.',
                'status'          => true,
            ],
            [
                'name'            => 'B\'Twin — Cycling',
                'slug'            => 'btwin-collection',
                'description'     => 'B\'Twin bikes, helmets, jerseys and cycling accessories.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 75,
                'seo_title'       => 'B\'Twin Bikes & Cycling Gear | Decathlon',
                'seo_description' => 'Shop B\'Twin road bikes, mountain bikes, helmets and cycling accessories.',
                'status'          => true,
            ],
            [
                'name'            => 'Nabaiji — Swimming',
                'slug'            => 'nabaiji-collection',
                'description'     => 'Nabaiji swimwear, goggles, caps and pool accessories.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'visible',
                'is_featured'     => false,
                'sort_order'      => 76,
                'seo_title'       => 'Nabaiji Swimwear & Swimming Gear | Decathlon',
                'seo_description' => 'Shop Nabaiji swimwear, goggles, swim caps and pool accessories.',
                'status'          => true,
            ],

            // ──────────────────────────────────────────────────────────────
            // FORM 8 — Hidden / Internal (not shown in nav)
            // ──────────────────────────────────────────────────────────────
            [
                'name'            => 'Clearance',
                'slug'            => 'clearance',
                'description'     => 'End of season clearance — massive discounts on selected products.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'hidden',
                'is_featured'     => false,
                'sort_order'      => 90,
                'seo_title'       => 'Clearance Sale | Decathlon',
                'seo_description' => 'Shop end-of-season clearance deals at Decathlon India.',
                'status'          => true,
            ],
            [
                'name'            => 'Staff Picks',
                'slug'            => 'staff-picks',
                'description'     => 'Products personally recommended by our Decathlon store staff.',
                'type'            => 'manual',
                'rules'           => null,
                'visibility'      => 'hidden',
                'is_featured'     => false,
                'sort_order'      => 91,
                'seo_title'       => 'Staff Picks | Decathlon',
                'seo_description' => 'Personal recommendations from Decathlon store staff.',
                'status'          => false,
            ],
        ];

        foreach ($forms as $data) {
            Collection::firstOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }

        $total    = Collection::count();
        $featured = Collection::where('is_featured', true)->count();
        $auto     = Collection::where('type', 'auto')->count();
        $manual   = Collection::where('type', 'manual')->count();

        $this->command->info("✅ Collections seeded — {$total} total | {$featured} featured | {$auto} auto | {$manual} manual");
        $this->command->info('   Form 1: Featured/Hero (4)  |  Form 2: By Sport (10)  |  Form 3: By Audience (4)');
        $this->command->info('   Form 4: By Feature (4)     |  Form 5: Seasonal (4)   |  Form 6: By Price (3)');
        $this->command->info('   Form 7: By Brand (7)       |  Form 8: Internal (2)');
    }
}
