<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\EmailCampaign;
use Carbon\Carbon;

class EmailCampaignSeeder extends Seeder
{
    public function run(): void
    {
        // Safe truncate — skip if table doesn't exist
        if (\Illuminate\Support\Facades\Schema::hasTable('email_campaigns')) {
            \App\Models\EmailCampaign::truncate();
        }

        $campaigns = [
            // 1 - Newsletter (sent)
            [
                'name'               => 'Monthly Newsletter — June 2025',
                'subject'            => '📰 Decathlon Monthly: New arrivals, tips & community stories',
                'preview_text'       => 'Your June roundup: new gear, training tips, and athlete spotlights.',
                'type'               => 'newsletter',
                'status'             => 'sent',
                'from_name'          => 'Decathlon Team',
                'from_email'         => 'newsletter@decathlon.com',
                'reply_to'           => 'newsletter@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 38500,
                'sent_count'         => 37800,
                'opened_count'       => 9450,
                'clicked_count'      => 1890,
                'unsubscribed_count' => 42,
                'bounced_count'      => 700,
                'tags'               => ['newsletter', 'monthly', 'june'],
                'scheduled_at'       => Carbon::now()->subDays(7),
                'sent_at'            => Carbon::now()->subDays(7),
                'content'            => '<h1>June 2025 Newsletter</h1><p>Here\'s what\'s new at Decathlon this month.</p>',
            ],
            // 2 - Newsletter (sent)
            [
                'name'               => 'Winter Sports Season Kickoff 2024',
                'subject'            => '❄️ Winter is here — Ski, snowboard & cold weather gear',
                'preview_text'       => 'The slopes are calling. Shop our full winter sports collection now.',
                'type'               => 'newsletter',
                'status'             => 'sent',
                'from_name'          => 'Decathlon Winter',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 41000,
                'sent_count'         => 40180,
                'opened_count'       => 10045,
                'clicked_count'      => 3014,
                'unsubscribed_count' => 61,
                'bounced_count'      => 820,
                'tags'               => ['winter', 'seasonal', 'ski'],
                'scheduled_at'       => Carbon::now()->subDays(60),
                'sent_at'            => Carbon::now()->subDays(60),
                'content'            => '<h1>Winter Sports Season Kickoff!</h1><p>Shop ski, snowboard and cold weather gear.</p>',
            ],
            // 3 - Promotional (scheduled)
            [
                'name'               => 'Summer Sale 2025 — Up to 50% Off',
                'subject'            => '☀️ Summer Sale is LIVE — Up to 50% off sports gear!',
                'preview_text'       => 'Don\'t miss our biggest summer sale. Shop now before stock runs out.',
                'type'               => 'promotional',
                'status'             => 'scheduled',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['summer', 'sale', 'promotional'],
                'scheduled_at'       => Carbon::now()->addDays(5),
                'sent_at'            => null,
                'content'            => '<h1>Summer Sale — Up to 50% Off!</h1><p>Shop the best deals on running, cycling, swimming and more.</p>',
            ],
            // 4 - Promotional (scheduled)
            [
                'name'               => 'Back to School Sports 2025',
                'subject'            => '🎒 Back to School: Gear up for the new season!',
                'preview_text'       => 'New school year, new gear. Shop PE essentials, team sports & more.',
                'type'               => 'promotional',
                'status'             => 'scheduled',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['seasonal', 'back-to-school', 'kids'],
                'scheduled_at'       => Carbon::now()->addDays(10),
                'sent_at'            => null,
                'content'            => '<h1>Back to School 2025</h1><p>Everything your kids need for a great school year.</p>',
            ],
            // 5 - Draft
            [
                'name'               => 'Autumn Collection Preview 2025',
                'subject'            => '🍂 Sneak peek: Autumn 2025 collection is here',
                'preview_text'       => 'Be the first to see our new autumn arrivals before they go live.',
                'type'               => 'newsletter',
                'status'             => 'draft',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => null,
                'audience_type'      => 'all',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['autumn', 'preview', 'draft'],
                'scheduled_at'       => null,
                'sent_at'            => null,
                'content'            => null,
            ],
            // 6 - Draft
            [
                'name'               => 'Black Friday 2025 Teaser',
                'subject'            => '🖤 Black Friday is coming — Get ready for the biggest sale of the year',
                'preview_text'       => 'Mark your calendar. Black Friday deals start November 28.',
                'type'               => 'promotional',
                'status'             => 'draft',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => null,
                'audience_type'      => 'all',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['black-friday', 'teaser', 'promotional'],
                'scheduled_at'       => null,
                'sent_at'            => null,
                'content'            => null,
            ],
            // 7 - Welcome (sent)
            [
                'name'               => 'Welcome to Decathlon — New Member Onboarding',
                'subject'            => '👋 Welcome to Decathlon! Here\'s your 10% off first order',
                'preview_text'       => 'Thanks for joining! Enjoy 10% off your first purchase with code WELCOME10.',
                'type'               => 'welcome',
                'status'             => 'sent',
                'from_name'          => 'Decathlon',
                'from_email'         => 'welcome@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'new_customers',
                'total_recipients'   => 1240,
                'sent_count'         => 1228,
                'opened_count'       => 736,
                'clicked_count'      => 294,
                'unsubscribed_count' => 3,
                'bounced_count'      => 12,
                'tags'               => ['welcome', 'onboarding', 'new-customer'],
                'scheduled_at'       => Carbon::now()->subDays(3),
                'sent_at'            => Carbon::now()->subDays(3),
                'content'            => '<h1>Welcome to Decathlon!</h1><p>Use code WELCOME10 for 10% off your first order.</p>',
            ],
            // 8 - Abandoned Cart (sent)
            [
                'name'               => 'Abandoned Cart Recovery — Week 24',
                'subject'            => '🛒 You left something behind! Complete your order today',
                'preview_text'       => 'Your cart is waiting. Items may sell out — complete your purchase now.',
                'type'               => 'abandoned_cart',
                'status'             => 'sent',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'specific_segment',
                'total_recipients'   => 3200,
                'sent_count'         => 3136,
                'opened_count'       => 1254,
                'clicked_count'      => 502,
                'unsubscribed_count' => 9,
                'bounced_count'      => 64,
                'tags'               => ['abandoned-cart', 'recovery', 'automated'],
                'scheduled_at'       => Carbon::now()->subDays(5),
                'sent_at'            => Carbon::now()->subDays(5),
                'content'            => '<h1>Your cart is waiting!</h1><p>Complete your purchase before items sell out.</p>',
            ],
            // 9 - Re-engagement (sent)
            [
                'name'               => 'We Miss You — Win-Back Campaign Q2',
                'subject'            => '💌 We miss you! Here\'s 15% off to come back',
                'preview_text'       => 'It\'s been a while. We\'d love to have you back with an exclusive discount.',
                'type'               => 're_engagement',
                'status'             => 'sent',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'inactive_customers',
                'total_recipients'   => 8900,
                'sent_count'         => 8722,
                'opened_count'       => 1744,
                'clicked_count'      => 523,
                'unsubscribed_count' => 267,
                'bounced_count'      => 178,
                'tags'               => ['re-engagement', 'win-back', 'inactive'],
                'scheduled_at'       => Carbon::now()->subDays(30),
                'sent_at'            => Carbon::now()->subDays(30),
                'content'            => '<h1>We miss you!</h1><p>Use code COMEBACK15 for 15% off your next order.</p>',
            ],
            // 10 - Product Launch (scheduled)
            [
                'name'               => 'New Kiprun KD900X Launch — July 2025',
                'subject'            => '🚀 Introducing the Kiprun KD900X — Our fastest shoe yet',
                'preview_text'       => 'The wait is over. Meet the Kiprun KD900X — engineered for speed.',
                'type'               => 'product_launch',
                'status'             => 'scheduled',
                'from_name'          => 'Decathlon Running',
                'from_email'         => 'running@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['product-launch', 'running', 'kiprun'],
                'scheduled_at'       => Carbon::now()->addDays(3),
                'sent_at'            => null,
                'content'            => '<h1>Introducing the Kiprun KD900X</h1><p>Our fastest running shoe yet. Available July 2025.</p>',
            ],
            // 11 - Paused
            [
                'name'               => 'Loyalty Rewards — Double Points Week',
                'subject'            => '⭐ Double points this week only — Loyalty members exclusive',
                'preview_text'       => 'Earn double loyalty points on every purchase this week.',
                'type'               => 'promotional',
                'status'             => 'paused',
                'from_name'          => 'Decathlon Loyalty',
                'from_email'         => 'loyalty@decathlon.com',
                'reply_to'           => 'support@decathlon.com',
                'audience_type'      => 'all',
                'total_recipients'   => 18500,
                'sent_count'         => 9016,
                'opened_count'       => 2704,
                'clicked_count'      => 811,
                'unsubscribed_count' => 18,
                'bounced_count'      => 184,
                'tags'               => ['loyalty', 'rewards', 'paused'],
                'scheduled_at'       => Carbon::now()->subDays(2),
                'sent_at'            => null,
                'content'            => '<h1>Double Points Week!</h1><p>Earn double loyalty points on every purchase this week.</p>',
            ],
            // 12 - Cancelled
            [
                'name'               => 'Spring Fitness Challenge 2025',
                'subject'            => '🌱 Join our Spring Fitness Challenge — Win amazing prizes!',
                'preview_text'       => '30 days, 30 challenges. Are you ready to transform your fitness?',
                'type'               => 're_engagement',
                'status'             => 'cancelled',
                'from_name'          => 'Decathlon',
                'from_email'         => 'noreply@decathlon.com',
                'reply_to'           => null,
                'audience_type'      => 'inactive_customers',
                'total_recipients'   => 0,
                'sent_count'         => 0,
                'opened_count'       => 0,
                'clicked_count'      => 0,
                'unsubscribed_count' => 0,
                'bounced_count'      => 0,
                'tags'               => ['spring', 'fitness', 'challenge'],
                'scheduled_at'       => null,
                'sent_at'            => null,
                'content'            => null,
            ],
        ];

        foreach ($campaigns as $data) {
            EmailCampaign::create($data);
        }

        $this->command->info('EmailCampaignSeeder: 12 campaigns seeded successfully.');
    }
}
