<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Promotion;
use Carbon\Carbon;

class PromotionSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $promotions = [

            // ── FLASH SALES ──────────────────────────────────────────────
            [
                'name'              => 'Summer Flash Sale 50% OFF',
                'slug'              => 'summer-flash-sale-50',
                'description'       => 'Limited time flash sale — 50% off on all summer sports gear.',
                'type'              => 'flash_sale',
                'discount_value'    => 50,
                'max_discount_amount'=> 1500,
                'min_order_amount'  => 999,
                'usage_limit'       => 500,
                'usage_per_user'    => 1,
                'used_count'        => 127,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->subDays(2),
                'ends_at'           => $now->copy()->addDays(3),
                'badge_text'        => '⚡ 50% OFF',
                'badge_color'       => '#f97316',
                'show_countdown'    => true,
                'show_on_homepage'  => true,
                'priority'          => 10,
                'is_active'         => true,
            ],
            [
                'name'              => 'Weekend Flash Deal 30% OFF',
                'slug'              => 'weekend-flash-30',
                'description'       => 'This weekend only — 30% off on running shoes and apparel.',
                'type'              => 'flash_sale',
                'discount_value'    => 30,
                'max_discount_amount'=> 800,
                'min_order_amount'  => 599,
                'usage_limit'       => 200,
                'usage_per_user'    => 2,
                'used_count'        => 89,
                'applies_to'        => 'specific_categories',
                'applicable_ids'    => [1, 2, 3],
                'starts_at'         => $now->copy()->subDay(),
                'ends_at'           => $now->copy()->addDays(2),
                'badge_text'        => '⚡ 30% OFF',
                'badge_color'       => '#ef4444',
                'show_countdown'    => true,
                'show_on_homepage'  => false,
                'priority'          => 8,
                'is_active'         => true,
            ],

            // ── PERCENTAGE DISCOUNTS ─────────────────────────────────────
            [
                'name'              => 'New Customer 20% OFF',
                'slug'              => 'new-customer-20',
                'description'       => 'Welcome offer — 20% off on your first order.',
                'type'              => 'percentage',
                'discount_value'    => 20,
                'max_discount_amount'=> 500,
                'min_order_amount'  => 499,
                'usage_limit'       => null,
                'usage_per_user'    => 1,
                'used_count'        => 342,
                'applies_to'        => 'all',
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '20% OFF',
                'badge_color'       => '#0082C3',
                'show_countdown'    => false,
                'show_on_homepage'  => true,
                'priority'          => 5,
                'is_active'         => true,
            ],
            [
                'name'              => 'Fitness Month 15% OFF',
                'slug'              => 'fitness-month-15',
                'description'       => 'Celebrate fitness month with 15% off on all gym equipment.',
                'type'              => 'percentage',
                'discount_value'    => 15,
                'max_discount_amount'=> 1000,
                'min_order_amount'  => 1499,
                'usage_limit'       => 1000,
                'usage_per_user'    => 3,
                'used_count'        => 456,
                'applies_to'        => 'specific_categories',
                'applicable_ids'    => [4, 5],
                'starts_at'         => $now->copy()->startOfMonth(),
                'ends_at'           => $now->copy()->endOfMonth(),
                'badge_text'        => '15% OFF',
                'badge_color'       => '#22c55e',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 4,
                'is_active'         => true,
            ],
            [
                'name'              => 'Monsoon Sale 25% OFF',
                'slug'              => 'monsoon-sale-25',
                'description'       => 'Monsoon season special — 25% off on waterproof gear.',
                'type'              => 'percentage',
                'discount_value'    => 25,
                'max_discount_amount'=> 750,
                'min_order_amount'  => 799,
                'usage_limit'       => 300,
                'usage_per_user'    => 2,
                'used_count'        => 0,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->addDays(10),
                'ends_at'           => $now->copy()->addDays(40),
                'badge_text'        => '🌧 25% OFF',
                'badge_color'       => '#6366f1',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 3,
                'is_active'         => true,
            ],

            // ── FIXED AMOUNT ─────────────────────────────────────────────
            [
                'name'              => 'Flat ₹200 OFF on ₹999+',
                'slug'              => 'flat-200-off-999',
                'description'       => 'Get flat ₹200 off on orders above ₹999.',
                'type'              => 'fixed_amount',
                'discount_value'    => 200,
                'max_discount_amount'=> null,
                'min_order_amount'  => 999,
                'usage_limit'       => null,
                'usage_per_user'    => 5,
                'used_count'        => 1203,
                'applies_to'        => 'all',
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '₹200 OFF',
                'badge_color'       => '#0082C3',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 2,
                'is_active'         => true,
            ],
            [
                'name'              => 'Flat ₹500 OFF on ₹2499+',
                'slug'              => 'flat-500-off-2499',
                'description'       => 'Big order? Save ₹500 on orders above ₹2499.',
                'type'              => 'fixed_amount',
                'discount_value'    => 500,
                'max_discount_amount'=> null,
                'min_order_amount'  => 2499,
                'usage_limit'       => null,
                'usage_per_user'    => 3,
                'used_count'        => 678,
                'applies_to'        => 'all',
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '₹500 OFF',
                'badge_color'       => '#7c3aed',
                'show_countdown'    => false,
                'show_on_homepage'  => true,
                'priority'          => 2,
                'is_active'         => true,
            ],

            // ── FREE SHIPPING ────────────────────────────────────────────
            [
                'name'              => 'Free Shipping on ₹499+',
                'slug'              => 'free-shipping-499',
                'description'       => 'Free delivery on all orders above ₹499.',
                'type'              => 'free_shipping',
                'discount_value'    => 0,
                'min_order_amount'  => 499,
                'usage_limit'       => null,
                'usage_per_user'    => null,
                'used_count'        => 5621,
                'applies_to'        => 'all',
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '🚚 Free Ship',
                'badge_color'       => '#059669',
                'show_countdown'    => false,
                'show_on_homepage'  => true,
                'priority'          => 1,
                'is_active'         => true,
            ],
            [
                'name'              => 'Free Shipping Weekend',
                'slug'              => 'free-shipping-weekend',
                'description'       => 'Free shipping on all orders this weekend — no minimum.',
                'type'              => 'free_shipping',
                'discount_value'    => 0,
                'min_order_amount'  => 0,
                'usage_limit'       => null,
                'usage_per_user'    => null,
                'used_count'        => 0,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->next('Saturday'),
                'ends_at'           => $now->copy()->next('Sunday')->endOfDay(),
                'badge_text'        => '🚚 Free Ship',
                'badge_color'       => '#059669',
                'show_countdown'    => true,
                'show_on_homepage'  => false,
                'priority'          => 6,
                'is_active'         => true,
            ],

            // ── BUY X GET Y ──────────────────────────────────────────────
            [
                'name'              => 'Buy 2 Get 1 Free',
                'slug'              => 'buy-2-get-1-free',
                'description'       => 'Buy any 2 products and get the 3rd one absolutely free.',
                'type'              => 'buy_x_get_y',
                'discount_value'    => 0,
                'buy_quantity'      => 2,
                'get_quantity'      => 1,
                'get_discount_percent'=> 100,
                'min_order_amount'  => null,
                'usage_limit'       => 500,
                'usage_per_user'    => 2,
                'used_count'        => 234,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->subDays(5),
                'ends_at'           => $now->copy()->addDays(25),
                'badge_text'        => '🎁 B2G1',
                'badge_color'       => '#db2777',
                'show_countdown'    => false,
                'show_on_homepage'  => true,
                'priority'          => 7,
                'is_active'         => true,
            ],
            [
                'name'              => 'Buy 3 Get 1 at 50% OFF',
                'slug'              => 'buy-3-get-1-half',
                'description'       => 'Buy 3 items and get the 4th at 50% off.',
                'type'              => 'buy_x_get_y',
                'discount_value'    => 0,
                'buy_quantity'      => 3,
                'get_quantity'      => 1,
                'get_discount_percent'=> 50,
                'min_order_amount'  => null,
                'usage_limit'       => 300,
                'usage_per_user'    => 3,
                'used_count'        => 89,
                'applies_to'        => 'specific_categories',
                'applicable_ids'    => [1, 2, 3, 4],
                'starts_at'         => $now->copy()->subDays(3),
                'ends_at'           => $now->copy()->addDays(15),
                'badge_text'        => '🎁 B3G1 50%',
                'badge_color'       => '#9333ea',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 6,
                'is_active'         => true,
            ],

            // ── BUNDLE DEALS ─────────────────────────────────────────────
            [
                'name'              => 'Cricket Starter Kit Bundle',
                'slug'              => 'cricket-starter-bundle',
                'description'       => 'Complete cricket starter kit — bat, ball, pads at special bundle price.',
                'type'              => 'bundle',
                'discount_value'    => 20,
                'min_order_amount'  => 1999,
                'usage_limit'       => 100,
                'usage_per_user'    => 1,
                'used_count'        => 45,
                'applies_to'        => 'specific_categories',
                'applicable_ids'    => [3],
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '📦 Bundle',
                'badge_color'       => '#0891b2',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 3,
                'is_active'         => true,
            ],
            [
                'name'              => 'Yoga Complete Set Bundle',
                'slug'              => 'yoga-complete-bundle',
                'description'       => 'Yoga mat + blocks + strap + bag — complete set at 18% off.',
                'type'              => 'bundle',
                'discount_value'    => 18,
                'min_order_amount'  => 1499,
                'usage_limit'       => 150,
                'usage_per_user'    => 1,
                'used_count'        => 67,
                'applies_to'        => 'specific_categories',
                'applicable_ids'    => [5],
                'starts_at'         => null,
                'ends_at'           => null,
                'badge_text'        => '📦 Bundle',
                'badge_color'       => '#0891b2',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 3,
                'is_active'         => true,
            ],

            // ── EXPIRED (for history) ────────────────────────────────────
            [
                'name'              => 'Republic Day Sale 40% OFF',
                'slug'              => 'republic-day-40',
                'description'       => 'Republic Day special — 40% off sitewide.',
                'type'              => 'percentage',
                'discount_value'    => 40,
                'max_discount_amount'=> 1200,
                'min_order_amount'  => 799,
                'usage_limit'       => 2000,
                'usage_per_user'    => 2,
                'used_count'        => 1987,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->subDays(120),
                'ends_at'           => $now->copy()->subDays(118),
                'badge_text'        => '🇮🇳 40% OFF',
                'badge_color'       => '#f97316',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 0,
                'is_active'         => true,
            ],
            [
                'name'              => 'Holi Special 35% OFF',
                'slug'              => 'holi-special-35',
                'description'       => 'Holi festival special discount on all outdoor sports.',
                'type'              => 'percentage',
                'discount_value'    => 35,
                'max_discount_amount'=> 900,
                'min_order_amount'  => 699,
                'usage_limit'       => 1000,
                'usage_per_user'    => 1,
                'used_count'        => 876,
                'applies_to'        => 'all',
                'starts_at'         => $now->copy()->subDays(60),
                'ends_at'           => $now->copy()->subDays(58),
                'badge_text'        => '🎨 35% OFF',
                'badge_color'       => '#ec4899',
                'show_countdown'    => false,
                'show_on_homepage'  => false,
                'priority'          => 0,
                'is_active'         => false,
            ],
        ];

        foreach ($promotions as $data) {
            Promotion::firstOrCreate(['slug' => $data['slug']], $data);
        }

        $total     = Promotion::count();
        $active    = Promotion::where('is_active', true)->where(fn($q) => $q->whereNull('ends_at')->orWhere('ends_at', '>=', now()))->count();
        $flashSale = Promotion::where('type', 'flash_sale')->count();

        $this->command->info("✅ Promotions seeded — {$total} total | {$active} active | {$flashSale} flash sales");
        $this->command->info('   Types: Flash Sale(2) | Percentage(3) | Fixed(2) | Free Ship(2) | BxGy(2) | Bundle(2) | Expired(2)');
    }
}
