<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ProductReview;
use App\Models\Product;

class ReviewSeeder extends Seeder
{
    public function run(): void
    {
        $product = Product::first();
        $productId = $product ? $product->id : 1;

        $products = Product::inRandomOrder()->limit(5)->pluck('id')->toArray();
        if (empty($products)) $products = [1];

        $reviews = [
            [
                'reviewer_name'  => 'Arjun Sharma',
                'reviewer_email' => 'arjun.sharma@gmail.com',
                'rating'         => 5,
                'title'          => 'Excellent quality, totally worth it!',
                'body'           => 'I bought this for my morning runs and it has been fantastic. The grip is superb and the material is very breathable. Highly recommend to all fitness enthusiasts.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => true,
                'helpful_count'  => 24,
                'source'         => 'website',
                'admin_reply'    => 'Thank you Arjun! We are glad you love the product. Keep running!',
                'replied_at'     => now()->subDays(2),
            ],
            [
                'reviewer_name'  => 'Priya Nair',
                'reviewer_email' => 'priya.nair@yahoo.com',
                'rating'         => 4,
                'title'          => 'Good product, minor sizing issue',
                'body'           => 'Overall a great product. The quality is good and it looks exactly like the pictures. I had a minor sizing issue but the customer support was very helpful. Would buy again.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 12,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Rahul Verma',
                'reviewer_email' => 'rahul.verma@hotmail.com',
                'rating'         => 5,
                'title'          => 'Best sports gear I have ever used',
                'body'           => 'Decathlon never disappoints. This product is durable, comfortable and great value for money. I use it every day for my gym sessions and it holds up perfectly.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => true,
                'helpful_count'  => 31,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Sneha Patel',
                'reviewer_email' => 'sneha.patel@gmail.com',
                'rating'         => 3,
                'title'          => 'Average product, expected better',
                'body'           => 'The product is okay but I expected better quality at this price point. The stitching came loose after a month of use. Not sure if I would recommend it.',
                'status'         => 'pending',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 5,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Vikram Singh',
                'reviewer_email' => 'vikram.singh@gmail.com',
                'rating'         => 5,
                'title'          => 'Perfect for outdoor cycling',
                'body'           => 'I use this for my weekend cycling trips and it is absolutely perfect. Lightweight, durable and very comfortable. The design is also very stylish. 10/10 would recommend.',
                'status'         => 'approved',
                'verified_purchase' => false,
                'featured'       => false,
                'helpful_count'  => 18,
                'source'         => 'admin',
            ],
            [
                'reviewer_name'  => 'Ananya Krishnan',
                'reviewer_email' => 'ananya.k@gmail.com',
                'rating'         => 2,
                'title'          => 'Disappointed with the quality',
                'body'           => 'The product looks good in pictures but the actual quality is quite poor. The material feels cheap and the color faded after just two washes. Very disappointed.',
                'status'         => 'rejected',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 3,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Karthik Reddy',
                'reviewer_email' => 'karthik.reddy@outlook.com',
                'rating'         => 4,
                'title'          => 'Great for yoga and stretching',
                'body'           => 'I bought this for my yoga sessions and it works great. The material is soft and flexible. The only downside is that it takes a bit long to dry after washing.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 9,
                'source'         => 'website',
                'admin_reply'    => 'Thanks Karthik! We appreciate your feedback. We will pass this on to our product team.',
                'replied_at'     => now()->subDays(5),
            ],
            [
                'reviewer_name'  => 'Meera Joshi',
                'reviewer_email' => 'meera.joshi@gmail.com',
                'rating'         => 5,
                'title'          => 'Amazing value for money',
                'body'           => 'I have been using Decathlon products for years and they never disappoint. This one is no exception. Great quality, great price. My whole family uses Decathlon gear now.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => true,
                'helpful_count'  => 42,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Suresh Kumar',
                'reviewer_email' => 'suresh.kumar@gmail.com',
                'rating'         => 1,
                'title'          => 'Received wrong product',
                'body'           => 'I ordered size L but received size M. Very frustrating experience. The product itself might be good but I cannot review it properly since I got the wrong size.',
                'status'         => 'pending',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 7,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Divya Menon',
                'reviewer_email' => 'divya.menon@gmail.com',
                'rating'         => 4,
                'title'          => 'Good for swimming training',
                'body'           => 'I use this for my swimming training sessions. It is comfortable and durable. The chlorine resistance is good. Would definitely buy again.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 15,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Aditya Bhatt',
                'reviewer_email' => 'aditya.bhatt@gmail.com',
                'rating'         => 5,
                'title'          => 'Top notch football gear',
                'body'           => 'I play football every weekend and this gear has been a game changer. The grip, the comfort, the durability — everything is top notch. My teammates are all jealous!',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 28,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Pooja Gupta',
                'reviewer_email' => 'pooja.gupta@gmail.com',
                'rating'         => 3,
                'title'          => 'Decent but not exceptional',
                'body'           => 'The product is decent for the price. Nothing extraordinary but gets the job done. I have used better products from other brands but for the price this is acceptable.',
                'status'         => 'pending',
                'verified_purchase' => false,
                'featured'       => false,
                'helpful_count'  => 2,
                'source'         => 'admin',
            ],
            [
                'reviewer_name'  => 'Rajesh Nambiar',
                'reviewer_email' => 'rajesh.nambiar@gmail.com',
                'rating'         => 5,
                'title'          => 'Perfect trekking companion',
                'body'           => 'I took this on a 3-day trek in the Himalayas and it performed brilliantly. Waterproof, durable and very comfortable. Decathlon makes the best trekking gear in this price range.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => true,
                'helpful_count'  => 56,
                'source'         => 'website',
                'admin_reply'    => 'Wow, the Himalayas! That is amazing Rajesh. Thank you for sharing your experience with us!',
                'replied_at'     => now()->subDays(1),
            ],
            [
                'reviewer_name'  => 'Lakshmi Iyer',
                'reviewer_email' => 'lakshmi.iyer@gmail.com',
                'rating'         => 4,
                'title'          => 'Great for badminton',
                'body'           => 'I play badminton 4 times a week and this product has been very reliable. Good grip, comfortable fit and holds up well under intense play. Recommended for regular players.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 11,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Nikhil Desai',
                'reviewer_email' => 'nikhil.desai@gmail.com',
                'rating'         => 2,
                'title'          => 'Not as described',
                'body'           => 'The product description was misleading. The actual product is quite different from what was shown. The material quality is also not up to the mark. Would not recommend.',
                'status'         => 'spam',
                'verified_purchase' => false,
                'featured'       => false,
                'helpful_count'  => 0,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Kavitha Rajan',
                'reviewer_email' => 'kavitha.rajan@gmail.com',
                'rating'         => 5,
                'title'          => 'Excellent for marathon training',
                'body'           => 'I am training for my first marathon and this product has been essential. Lightweight, breathable and very comfortable for long runs. Cannot imagine training without it now.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 33,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Sanjay Tiwari',
                'reviewer_email' => 'sanjay.tiwari@gmail.com',
                'rating'         => 4,
                'title'          => 'Good cricket gear',
                'body'           => 'I play cricket at the club level and this gear is perfect for that. Good quality, comfortable and reasonably priced. The only thing I would improve is the packaging.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 8,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Ritu Agarwal',
                'reviewer_email' => 'ritu.agarwal@gmail.com',
                'rating'         => 5,
                'title'          => 'Best purchase this year',
                'body'           => 'This is honestly the best sports purchase I have made this year. The quality is outstanding and it has made my workouts so much more enjoyable. Thank you Decathlon!',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 19,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Harish Pillai',
                'reviewer_email' => 'harish.pillai@gmail.com',
                'rating'         => 3,
                'title'          => 'Okay for casual use',
                'body'           => 'If you are a casual sports person this product is fine. But for serious athletes I would recommend something more professional. It is good for the price though.',
                'status'         => 'pending',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 4,
                'source'         => 'website',
            ],
            [
                'reviewer_name'  => 'Deepa Chandran',
                'reviewer_email' => 'deepa.chandran@gmail.com',
                'rating'         => 5,
                'title'          => 'Superb quality, fast delivery',
                'body'           => 'The product quality is superb and the delivery was very fast. I ordered on Monday and received it by Wednesday. The packaging was also very good. Will definitely order again.',
                'status'         => 'approved',
                'verified_purchase' => true,
                'featured'       => false,
                'helpful_count'  => 22,
                'source'         => 'website',
            ],
        ];

        foreach ($reviews as $i => $review) {
            $pid = isset($products[$i % count($products)]) ? $products[$i % count($products)] : $productId;
            ProductReview::create(array_merge($review, [
                'product_id' => $pid,
                'source'     => $review['source'] ?? 'website',
                'created_at' => now()->subDays(rand(1, 90)),
                'updated_at' => now()->subDays(rand(0, 30)),
            ]));
        }

        $this->command->info('✅ 20 product reviews seeded successfully.');
    }
}
